import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Self-hosted Geist (offline-safe). Replaces next/font/google, which needs
// fonts.googleapis.com at build time.
const geistSans = localFont({
  src: [
    { path: "./fonts/geist-latin-400-normal.woff2", weight: "400" },
    { path: "./fonts/geist-latin-700-normal.woff2", weight: "700" },
  ],
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: [
    { path: "./fonts/geist-mono-latin-400-normal.woff2", weight: "400" },
    { path: "./fonts/geist-mono-latin-700-normal.woff2", weight: "700" },
  ],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
